package RemoteInterface;

/**
* RemoteInterface/ServerRemoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerRemote.idl
* Monday, October 30, 2017 2:22:36 PM EDT
*/

public final class ServerRemoteHolder implements org.omg.CORBA.portable.Streamable
{
  public RemoteInterface.ServerRemote value = null;

  public ServerRemoteHolder ()
  {
  }

  public ServerRemoteHolder (RemoteInterface.ServerRemote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RemoteInterface.ServerRemoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RemoteInterface.ServerRemoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RemoteInterface.ServerRemoteHelper.type ();
  }

}
