package RemoteInterface;


/**
* RemoteInterface/ServerRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerRemote.idl
* Tuesday, October 24, 2017 1:55:50 AM EDT
*/

public interface ServerRemoteOperations 
{
  String[] AddRecord (String date, short room, String[] timeslots);
  boolean[] DeleteRecord (String date, short room, String[] timeslots);
  String Book (String stu_id, String campus, String date, short room, String timeslots);
  boolean CancelBook (String booking_id, String stu_id);
  String GetAvailTimeSlots (String date);
  String ChangeReservation (String stu_id, String booking_id, String new_campus_name, String new_room_no, String new_timeslot);
} // interface ServerRemoteOperations
