package RemoteInterface;


/**
* RemoteInterface/ServerRemotePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerRemote.idl
* Wednesday, October 18, 2017 11:28:08 PM EDT
*/

public abstract class ServerRemotePOA extends org.omg.PortableServer.Servant
 implements RemoteInterface.ServerRemoteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("AddRecord", new java.lang.Integer (0));
    _methods.put ("DeleteRecord", new java.lang.Integer (1));
    _methods.put ("Book", new java.lang.Integer (2));
    _methods.put ("CancelBook", new java.lang.Integer (3));
    _methods.put ("GetAvailTimeSlots", new java.lang.Integer (4));
    _methods.put ("ChangeReservation", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // RemoteInterface/ServerRemote/AddRecord
       {
         String date = in.read_string ();
         short room = in.read_ushort ();
         String timeslots[] = RemoteInterface.ListOfStringHelper.read (in);
         String $result[] = null;
         $result = this.AddRecord (date, room, timeslots);
         out = $rh.createReply();
         RemoteInterface.ListOfStringHelper.write (out, $result);
         break;
       }

       case 1:  // RemoteInterface/ServerRemote/DeleteRecord
       {
         String date = in.read_string ();
         short room = in.read_ushort ();
         String timeslots[] = RemoteInterface.ListOfStringHelper.read (in);
         boolean $result[] = null;
         $result = this.DeleteRecord (date, room, timeslots);
         out = $rh.createReply();
         RemoteInterface.ListOfBoolHelper.write (out, $result);
         break;
       }

       case 2:  // RemoteInterface/ServerRemote/Book
       {
         String stu_id = in.read_string ();
         String campus = in.read_string ();
         String date = in.read_string ();
         short room = in.read_ushort ();
         String timeslots = in.read_string ();
         String $result = null;
         $result = this.Book (stu_id, campus, date, room, timeslots);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // RemoteInterface/ServerRemote/CancelBook
       {
         String booking_id = in.read_string ();
         String stu_id = in.read_string ();
         boolean $result = false;
         $result = this.CancelBook (booking_id, stu_id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // RemoteInterface/ServerRemote/GetAvailTimeSlots
       {
         String date = in.read_string ();
         String $result = null;
         $result = this.GetAvailTimeSlots (date);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // RemoteInterface/ServerRemote/ChangeReservation
       {
         String booking_id = in.read_string ();
         String new_campus_name = in.read_string ();
         String new_room_no = in.read_string ();
         String new_timeslot = in.read_string ();
         boolean $result = false;
         $result = this.ChangeReservation (booking_id, new_campus_name, new_room_no, new_timeslot);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RemoteInterface/ServerRemote:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerRemote _this() 
  {
    return ServerRemoteHelper.narrow(
    super._this_object());
  }

  public ServerRemote _this(org.omg.CORBA.ORB orb) 
  {
    return ServerRemoteHelper.narrow(
    super._this_object(orb));
  }


} // class ServerRemotePOA
