package RemoteInterface;


/**
* RemoteInterface/ServerRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerRemote.idl
* Monday, October 30, 2017 2:22:36 PM EDT
*/

public interface ServerRemote extends ServerRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerRemote
