package RemoteInterface;


/**
* RemoteInterface/ServerRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerRemote.idl
* Tuesday, October 24, 2017 1:55:50 AM EDT
*/

public interface ServerRemote extends ServerRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerRemote
