package RemoteInterface;


/**
* RemoteInterface/ServerRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerRemote.idl
* Wednesday, November 15, 2017 9:13:14 PM EST
*/

public interface ServerRemote extends ServerRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerRemote
