module RemoteInterface{

	typedef sequence<string> ListOfString;
	typedef sequence<boolean> ListOfBool;

	interface ServerRemote
	{
		boolean login(in string id);
		ListOfString createRoom(in string id, in string room, in string date, in ListOfString timeslots);
		ListOfBool deleteRoom(in string id, in string room, in string date, in ListOfString timeslots);
		string bookRoom(in string stu_id, in string campus, in string room, in string date, in string timeslots);
		boolean cancelBook(in string stu_id, in string bookingID);
		string getAvailableTimeslot(in string id, in string date);
		string changeReservation(in string stu_id, in string old_booking_id, in string new_campus_name, 
										in string new_room_no, in string new_timeslot);
	};
};

